"""Project EDGE's authorised, read-only Market Data Manager boundary."""

from .contracts import (
    AUTHORISED_FOR_PROJECT_EDGE_RESEARCH,
    MDM_SOURCE_AUTHORITY,
    MDM_PRODUCTION_SNAPSHOT,
    REQUIRED_COLUMN_TYPES,
    REQUIRED_SORT_KEYS,
    REQUIRED_TABLE_COLUMNS,
    REQUIRED_TABLES,
    TEST_ONLY_NON_PRODUCTION,
    TEST_ONLY_NOT_AUTHORISED,
    ContractError,
    MdmSnapshotManifest,
    MdmTableManifest,
)
from .fingerprint import (
    LOGICAL_ROWS_FINGERPRINT_VERSION,
    SCHEMA_FINGERPRINT_VERSION,
    LogicalRowsFingerprint,
    canonical_json_bytes,
    logical_rows_fingerprint,
    package_source_fingerprint,
    schema_fingerprint,
    sha256_bytes,
    sha256_file,
)
from .source import (
    SourceValidationError,
    VerifiedMdmSnapshot,
    VerifiedMdmTable,
    verify_mdm_snapshot,
)
from .pipeline import (
    DailySliceBuild,
    DailySliceRequest,
    PipelineError,
    build_daily_slice,
    load_daily_slice_request,
)
from .release import (
    MaterialisedArtifact,
    ReleaseError,
    approve_production_release,
    change_production_release_state,
    materialise_candidate,
    record_failed_build_attempt,
    verify_materialised_candidate,
    verify_production_access,
)
from .scope import (
    ProductionScopeApproval,
    ScopeApprovalError,
    assert_repository_production_gate_open,
    load_production_scope,
)

__all__ = [
    "AUTHORISED_FOR_PROJECT_EDGE_RESEARCH",
    "ContractError",
    "LOGICAL_ROWS_FINGERPRINT_VERSION",
    "MDM_SOURCE_AUTHORITY",
    "MDM_PRODUCTION_SNAPSHOT",
    "MdmSnapshotManifest",
    "MdmTableManifest",
    "LogicalRowsFingerprint",
    "DailySliceBuild",
    "DailySliceRequest",
    "MaterialisedArtifact",
    "PipelineError",
    "ProductionScopeApproval",
    "REQUIRED_COLUMN_TYPES",
    "REQUIRED_SORT_KEYS",
    "REQUIRED_TABLE_COLUMNS",
    "REQUIRED_TABLES",
    "SCHEMA_FINGERPRINT_VERSION",
    "SourceValidationError",
    "ScopeApprovalError",
    "ReleaseError",
    "TEST_ONLY_NON_PRODUCTION",
    "TEST_ONLY_NOT_AUTHORISED",
    "VerifiedMdmSnapshot",
    "VerifiedMdmTable",
    "canonical_json_bytes",
    "approve_production_release",
    "assert_repository_production_gate_open",
    "change_production_release_state",
    "build_daily_slice",
    "load_daily_slice_request",
    "load_production_scope",
    "logical_rows_fingerprint",
    "package_source_fingerprint",
    "schema_fingerprint",
    "sha256_bytes",
    "sha256_file",
    "verify_mdm_snapshot",
    "materialise_candidate",
    "record_failed_build_attempt",
    "verify_materialised_candidate",
    "verify_production_access",
]
